version: "3.8"

services:

  db:
    container_name: postgresdb
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: faztpassword
      POSTGRES_DB: curpdb
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
